version: "3"
services:
    db:
        image: mysql:latest
        volumes:
            - ./db_data:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
            - ./mysql.conf.d:/etc/mysql/conf.d
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: distance_postcode
            MYSQL_USER: distance_postcode
            MYSQL_PASSWORD: iJcKavrcajxuvpaGgrstiQ2N
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"

    web:
        image: nginx:latest
        restart: 'always'
        volumes:
            - ./www:/var/www/html
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        links:
            - php

    php:
        build:
            context: ./
            dockerfile: php.dockerfile
        volumes:
            - ./www:/var/www/html
            - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini
        ports:
            - "9000:9000"
    node:
        image: node:latest
        tty: true
        working_dir: "/home/node/app"
        environment:
            - NODE_ENV=local
        build:
            context: ./
            dockerfile: node.dockerfile
        volumes:
            - ./www:/home/node/app
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        ports:
            - "8002:80"
        environment:
            - PMA_ARBITRARY=1

volumes:
    db_data:
    www: